### ISSUE TITLE
Implement ICS PoC

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#105]
We are implementing a proof of concept of ICS. Let's build the PoC first and then discuss improvements.

- [x] Import the ics-poc branch from the CodeChain repository
- [x] Import "Implement IBC client RPCs PR" from CodeChain ([link](https://github.com/CodeChain-io/codechain/pull/1849))
- [x] Use Toplevel transaction instead of custom action handler. Custom action handler will be removed soon. #122
- [x] Update light client to use real light client logic
  - [x] Add validator set hash in the header #153
- [x] Implement Vector commitment
  - [x] Implement Merkle proof https://github.com/CodeChain-io/rust-merkle-trie/pull/15
- [x] Implement Connection #156 
- [x] Implement Channel & Packets https://github.com/CodeChain-io/foundry/issues/197
- [x] Implement Relayer #201 
- [x] Implement a test scenario #201 

## Decisions

We will implement the handler module before the module system is introduced. We will add a wrapper module that wraps the handler API that is written using Rust in Foundry as a module.

## Related issues

* Make a module programmer be able to implement their light client type. #123

**Comment by junha1** [comment]
So we've already done something about ICS on CodeChain but not a single byte in foundry?

**Comment by junha1** [comment]
Then no more in CodeChain until we completely implement it in foundry first?

**Comment by majecty** [comment]
Yes, we will implement it in Foundry first.

**Comment by majecty** [comment]
DONE. I added other issues and PR links in the description.
