### ISSUE TITLE
Foundry v0.1.0

### ISSUE THREAD

**Issue by junha1** [CodeChain-io/foundry#511]
## TODOs
- [x] Complete DB's module subspace separation
- [x] Finalize Engine interface and make the consensus engine use that properly
- [x] https://github.com/CodeChain-io/foundry/pull/510
- [x] Write docs for `module-rt`
- [x] Write a doc for coordinator-module interface
- [x] Review commits and merge into master
- [x] Implement all essential GraphQL
- [x] Update license preambles (mold files are still with Affero)

## Might be TODOs (but might be deferred)
- Move various types/traits/utilities to `foundry-module-rt`
- Update chain-level RPCs into GraphQL queries
- Implement a simple JS-SDK
- Write tests running with JS-SDK

## Issues/PRs that will be closed with `v0.1.0`
- https://github.com/CodeChain-io/foundry/pull/318
- https://github.com/CodeChain-io/foundry/pull/375
- https://github.com/CodeChain-io/foundry/pull/409
- https://github.com/CodeChain-io/foundry/pull/437
- https://github.com/CodeChain-io/foundry/issues/5
- https://github.com/CodeChain-io/foundry/issues/6
- https://github.com/CodeChain-io/foundry/issues/383
- https://github.com/CodeChain-io/foundry/issues/417
- https://github.com/CodeChain-io/foundry/issues/449
- https://github.com/CodeChain-io/foundry/issues/490

**Comment by junha1** [comment]
There may be some changes regarding https://github.com/CodeChain-io/foundry/issues/512

**Comment by junha1** [comment]
We can construct a working network.
